### ISSUE TITLE
complete software checking...

### ISSUE THREAD

**Issue by mjks4545** [mjks4545/seedsschool#14]
please update git hub as soon as you check specific module of page...

**Comment by muhammadullah293** [comment]
1-checking visitor->done.
     1.1change main icon in visitor view->>done
2-teacher checking->>>>>done
     2.2->icon changes->done
     2.3-teacher view error->>done
     2.4-teacher detail view->modal bugs fixed.->>done
     2.5-bug in update teacher info->done
     2.6-teacher attendance->done
     2.7-teacher salary payment >>>>>>>>done
    2.8-teacher class status from number to label like active, deactive etc------->done
3- Academic Section--->done.
     3.1-subject->>>>>>>.done
     3.2-class->>>>>>>>done
     3.3-courses->>>>>>done
4-student ->>>>>>done
      4.1-add new student>>>>done
      4.1-view student detail->done
5.Other Staff->done
   5.1-view other staff bugs---->done
   5.2-update staff info ->>bug->done
   5,3-salary ---->bug->done
6-Expenses->>>>>>>done
   6.1- add expense->>>done
   6.2-view expense->>>>done
   6.3-search expense->>done
7-Reports->done
  7.1-some bug in weak reports-done
  7.2-some bugs in monthly reports-done
  7.3-some bugs in monthly finance-done
  7.4-some bugs in yearly reports-done
