### ISSUE TITLE
login

### ISSUE THREAD

**Issue by mjks4545** [mjks4545/seedsschool#2]
Create complete login system with roles...

1) Director or admin
2) Teacher
3) Student
4) gate keeper
5) Reciption ( Fee collection,visitor entry,student entry etc )

**Comment by mjks4545** [comment]
Also create views for each of them

**Comment by sherKhan1** [comment]
working on this still

**Comment by mjks4545** [comment]
ok please try to rap it up ASAP

**Comment by sherKhan1** [comment]
this is done
