### ISSUE TITLE
make reports

### ISSUE THREAD

**Issue by mjks4545** [mjks4545/seedsschool#4]
make reports like 
visitor report ( daily monthly weekly yearly ) 
student report ( daily monthly weekly yearly ) 
loss and profit report ( daily monthly weekly yearly )
balance sheet

**Comment by mjks4545** [comment]
1-visitor daily report
2-student daily report
3-weekly report for above both
4-finance daily reports
5-monthly reports
6-yearly reports
7-teacher

**Comment by mjks4545** [comment]
![screenshot_216](https://cloud.githubusercontent.com/assets/15276763/16543867/4ca467fe-4107-11e6-9239-e0adf4ba4d58.png)

**Comment by mjks4545** [comment]
ok keep posting

**Comment by Hazrat-Bilal** [comment]
errors are done

**Comment by Hazrat-Bilal** [comment]
ok now start working on reports

**Comment by Hazrat-Bilal** [comment]
daily students & visitor are done

**Comment by sherKhan1** [comment]
Start working

**Comment by sherKhan1** [comment]
Reports are done
