### ISSUE TITLE
create searches

### ISSUE THREAD

**Issue by mjks4545** [mjks4545/seedsschool#5]

**Comment by muhammadullah293** [comment]
correction in seeds projects
like gatekeeper,reception home pages . done

**Comment by muhammadullah293** [comment]
searches start......

**Comment by muhammadullah293** [comment]
expense search->>>>>.done,
search student->>>>>>>>>>done,
search visitor->>>>>>>>>done

**Comment by muhammadullah293** [comment]
admin Home page view adjustment in i n progress->>>>>>>.done
